apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "k3s-traefik-config.fullname" . }}
  labels:
    {{- include "k3s-traefik-config.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
