# Default values for k3s-traefik-config.
# Ref: https://github.com/philippwaller/helm-charts/tree/main/charts/k3s-traefik-config

## @section Common parameters
##

## @param nameOverride String to partially override common.names.fullname
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
fullnameOverride: ""


## @section Traefik Configuration
##

## @param traefikConfig [object] Traefik configuration
traefikConfig:
#  globalArguments:
#    - "--serversTransport.insecureSkipVerify=true"


## @section Docker Image
##

## @param image.repository job image repository
## @param image.pullPolicy image pull policy
## @param image.tag Overrides the image tag whose default is the chart appVersion.
image:
  repository: alpine
  pullPolicy: IfNotPresent
  tag: 3.15.0

## @param imagePullSecrets If defined, uses a Secret to pull an image from a private Docker registry or repository
imagePullSecrets: []


## @section Job Configuration
##

## @param podAnnotations Annotations to be added to the job pod
podAnnotations: {}

## @param podSecurityContext job pod-level security context
podSecurityContext: {}
  # fsGroup: 2000

## @param securityContext Security context
securityContext: {}


## @param resources Resource limits and requests
# Ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
resources: {}

## @param nodeSelector [object] Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector:
  node-role.kubernetes.io/control-plane: "true"

## @param tolerations Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## @param affinity Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}


## @section Service Account
##

serviceAccount:
  ## @param serviceAccount.create Specifies whether a service account should be created
  create: true
  ## @param serviceAccount.annotations Annotations to add to the service account
  annotations: {}
  ## @param serviceAccount.name The name of the service account to use.
  name: ""
