---
extends: default

ignore:
  /charts/

rules:
  document-start: disable
  quoted-strings:
    quote-type: double
    required: only-when-needed
  line-length:
    level: warning
    max: 110
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
