apiVersion: v1
kind: Endpoints
metadata:
  name: {{ include "external-service.fullname" . }}
  labels:
    {{- include "external-service.labels" . | nindent 4 }}
subsets:
  - addresses:
      - ip: {{ .Values.service.ip }}
    ports:
      - name: {{ .Values.service.name }}
        port: {{ .Values.service.targetPort }}
        protocol: {{ .Values.service.protocol }}
