apiVersion: v1
kind: Service
metadata:
  name: {{ include "external-service.fullname" . }}
  labels:
    {{- include "external-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq  (lower .Values.service.type) "externalname" }}
  externalName: {{ .Values.service.externalName }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.name }}
