# Default values for helm-controller.
# Ref: https://github.com/philippwaller/helm-charts/charts/helm-controller

## @section Common parameters
##

## @param nameOverride String to partially override common.names.fullname
nameOverride: ""

## @param fullnameOverride String to fully override common.names.fullname
fullnameOverride: ""


## @section Docker Image
##

## @param image.repository Inadyn image repository
## @param image.pullPolicy image pull policy
## @param image.tag Overrides the image tag whose default is the chart appVersion.
image:
  repository: rancher/helm-controller
  pullPolicy: IfNotPresent
  tag: ""

## @param imagePullSecrets If defined, uses a Secret to pull an image from a private Docker registry or repository
imagePullSecrets: []

## @section Container Configuration
##

## @param replicaCount The number of pods to run
replicaCount: 1

## @param podAnnotations Annotations to be added to the inadyn pod
podAnnotations: {}

## @param podSecurityContext Inadyn pod-level security context
podSecurityContext: {}
# fsGroup: 2000

## @param securityContext Security context
securityContext: {}
  ## capabilities:
  ##   drop:
  ##   - ALL
## readOnlyRootFilesystem: true
## runAsNonRoot: true
## runAsUser: 1000

## @param resources Resource limits and requests for inadyn
# Ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
resources: {}

## @param nodeSelector Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}

## @param tolerations Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## @param affinity Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}


## @section Service Account
##

## @param serviceAccount.create Specifies whether a service account should be created
## @param serviceAccount.annotations Annotations to add to the service account
## @param serviceAccount.name The name of the service account to use.
serviceAccount:
  create: true
  annotations: {}
  name: ""
