name: "Job: Conformity Check"
on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string

jobs:
  kubeconform:
    name: Kubeconform
    runs-on: ubuntu-latest
    if: toJson(inputs.configuration.matrix) != '[]'
    strategy:
      fail-fast: false
      matrix:
        chart: ${{ fromJson(inputs.configuration).matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v2.0
        with:
          version: v3.7.2

      - name: Render helm templates
        run: |
          helm template test ${{ matrix.chart.path }} \
            --kube-version ${{ matrix.chart.version }} \
            --output-dir build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:master
        with:
          entrypoint: /kubeconform
          args: >-
            -summary -output json -kubernetes-version ${{ matrix.chart.version }}
            -ignore-missing-schemas build
