name: "Job: Preparation"
on:
  workflow_call:
    outputs:
      configuration:
        description: CI configuration
        value: ${{ jobs.create-configuration.outputs.configuration }}

jobs:
  create-configuration:
    name: Create Configuration
    runs-on: ubuntu-latest
    outputs:
      configuration: ${{ steps.configuration.outputs.config }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Change detection
        uses: dorny/paths-filter@v2
        id: change-detection
        with:
          list-files: json
          filters: |
            charts:
              - 'charts/**'
            ci:
              - '.github/**'

      - name: Create configuration
        id: configuration
        run: |
          echo "Chart files changed?: ${{ steps.change-detection.outputs.charts }}"
          echo "Changed charts files: ${{ steps.change-detection.outputs.charts_files }}"
          echo "CI files changed?: ${{ steps.change-detection.outputs.ci }}"
          echo "Changed CI files: ${{ steps.change-detection.outputs.ci_files }}"
          output=$(./.github/scripts/generate-config.sh \
            '${{ steps.change-detection.outputs.ci }}' \
            '${{ steps.change-detection.outputs.charts_files }}' \
          )
          echo "::set-output name=config::$output"
          echo $output
