name: "Job: Test"
on:
  workflow_call:
    inputs:
      scope:
        required: true
        type: string
      k8s-versions:
        required: true
        type: string

jobs:
  test-deployment:
    name: Test Deployment
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s: ${{fromJson(inputs.k8s-versions)}}
        charts: ${{fromJson(inputs.scope)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v2.0
        with:
          version: v3.7.2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.0

      - name: Create kind ${{ matrix.k8s }} cluster
        uses: helm/kind-action@v1.2.0
        with:
          node_image: kindest/node:v${{ matrix.k8s }}

      - name: Deploy helm controller
        run: |
          helm repo add philippwaller https://charts.philippwaller.com
          helm install helm-controller philippwaller/helm-controller -n kube-system
        if: matrix.charts != 'charts/helm-controller'

      - name: Run chart-testing (install)
        run: ct install --config .github/ct.yaml --charts ${{ matrix.charts }}
