name: "Job: Content Check"
on:
  workflow_call:

jobs:
  pre-commit:
    name: Pre-Commit Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0
