name: "Job: Test"
on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string

jobs:
  test-deployment:
    name: Test Deployment
    runs-on: ubuntu-latest
    if: toJson(inputs.configuration.matrix) != '[]'
    strategy:
      fail-fast: false
      matrix:
        chart: ${{ fromJson(inputs.configuration).matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Create kind ${{ matrix.chart.version }} cluster
        uses: helm/kind-action@v1.4.0
        with:
          node_image: kindest/node:v${{ matrix.chart.version }}

      - name: Install custom resource definition
        run: |
          .github/scripts/install-custom-resource-definitions.sh \
            '${{ matrix.chart.sourceIndex }}' \
            '${{ inputs.configuration }}'

      - name: Run chart-testing (install)
        run: ct install --config .github/ct.yaml --charts ${{ matrix.chart.path }}
