name: "Job: Documentation"
on:
  workflow_call:
    inputs:
      configuration:
        required: true
        type: string
      commitChanges:
        required: false
        type: boolean
        default: false

jobs:
  update:
    name: Update Documentation
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        chart: ${{ fromJson(inputs.configuration).charts }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Checkout readme-generator-for-helm repo
        uses: actions/checkout@v3
        with:
          repository: bitnami-labs/readme-generator-for-helm
          path: readme-generator-for-helm

      - name: Install
        run: npm install ./readme-generator-for-helm

      - name: Update documentation files
        run: |
          $(npm bin)/readme-generator \
            -v ${{ matrix.chart.path }}/values.yaml \
            -r ${{ matrix.chart.path }}/README.md

      - name: Delete readme-generator-for-helm repo
        run: rm -rf ./readme-generator-for-helm

      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        if: ${{ inputs.commitChanges }}
        with:
          message: "docs(${{ matrix.chart.name }}): update helm chart documentation"
          pull: --rebase --autostash
          author_name: Philipp Waller
          author_email: 1090452+philippwaller@users.noreply.github.com
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
