name: "Flow: Integration Test"
on:
  pull_request:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - repository

jobs:
  pre-commit:
    name: Content Check
    uses: ./.github/workflows/job_pre-commit.yaml
  preparation:
    name: Preparation
    needs: [pre-commit]
    uses: ./.github/workflows/job_preparation.yaml
  documentation:
    name: Documentation
    needs: [preparation]
    uses: ./.github/workflows/job_documentation.yaml
    with:
      configuration: ${{ needs.preparation.outputs.configuration }}
      commitChanges: ${{ (github.event_name == 'pull_request') }}
  lint:
    name: Lint
    needs: [preparation]
    uses: ./.github/workflows/job_lint.yaml
    with:
      configuration: ${{ needs.preparation.outputs.configuration }}
  kubeconform:
    name: Conformity Check
    needs: [preparation]
    uses: ./.github/workflows/job_conformity-check.yaml
    with:
      configuration: ${{ needs.preparation.outputs.configuration }}
  test:
    name: Test
    needs: [preparation, lint, kubeconform]
    uses: ./.github/workflows/job_test-deployment.yaml
    with:
      configuration: ${{ needs.preparation.outputs.configuration }}
