name: "Flow: Integration Test"
on:
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    name: Content Check
    uses: ./.github/workflows/job_pre-commit.yaml
  preparation:
    name: Preparation
    needs: [pre-commit]
    uses: ./.github/workflows/job_preparation.yaml
  documentation:
    name: Documentation
    needs: [preparation]
    uses: ./.github/workflows/job_documentation.yaml
    with:
      scope: ${{needs.preparation.outputs.scope}}
      commit-changes: true
  lint:
    name: Lint
    needs: [preparation]
    uses: ./.github/workflows/job_lint.yaml
    with:
      scope: ${{needs.preparation.outputs.scope}}
  kubeconform:
    name: Conformity Check
    needs: [preparation]
    uses: ./.github/workflows/job_conformity-check.yaml
    with:
      scope: ${{needs.preparation.outputs.scope}}
      k8s-versions: ${{needs.preparation.outputs.k8s-versions}}
  test:
    name: Test
    needs: [preparation, lint, kubeconform]
    uses: ./.github/workflows/job_test-deployment.yaml
    with:
      scope: ${{needs.preparation.outputs.scope}}
      k8s-versions: ${{needs.preparation.outputs.k8s-versions}}
