name: "Flow: Update K8s Versions"
on:
  schedule:
    - cron: 0 6,18 * * *
  workflow_dispatch:

jobs:
  update-k8s-versions:
    name: Update K8s Versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug
        run: ls -l ./.github/scripts/update-k8s-versions.sh

      - name: Execute update script
        run: ./.github/scripts/update-k8s-versions.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-k8s-versions
          title: "build: Update list of supported Kubernetes versions"
          body: Update the list of supported Kubernetes versions.
          author: Philipp Waller <1090452+philippwaller@users.noreply.github.com>
          committer: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: "build: update the list of supported Kubernetes versions"
          assignees: philippwaller
          delete-branch: true
          base: main
          token: ${{ secrets.PAT }}
